networks:
  dokploy-network:
    external: true
    
services:
  staging-docs:
    image: registry.avey.ai/staging-api-docs:f02da0c2e04c85c0dbd52f7817c7d46a6f392cd9
    networks:
      - dokploy-network
    environment:
      - NEXT_PUBLIC_MODE=${NEXT_PUBLIC_MODE?}
      - GITHUB_APP_ID=${GITHUB_APP_ID?}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY?}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
