name: Build and Push Docs

on:
  push:
    branches:
      - dev

env:
  SERVICE_NAME: staging-api-docs
  IMAGE_REGISTRY: registry.avey.ai
  IMAGE_REGISTRY_USERNAME: avey
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.AVEY_REGISTRY_PASSWORD }}
  DOKPLOY_APPLICATION_ID: M7dapFpg0-Fj8HIRtmvF3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_REGISTRY_USERNAME }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        id: build
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          context: .
          file: Dockerfile
          target: production
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dokploy Deployment
        uses: ahmedabdou14/dokploy-deploy-gha@1.1.0
        with:
          auth_token: ${{ secrets.DOKPLOY_APIKEY }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          application_id: ${{ env.DOKPLOY_APPLICATION_ID }}

